title: ppluijten.dev
author: Pieter-Paul Luijten
description: >-
  The homepage for Pieter-Paul Luijten
url-pretty: "ppluijten.dev"
avatar: "/assets/img/avatar-icon.png"

# theme: minima
remote_theme: daattali/beautiful-jekyll@6.0.1
plugins:
  - jekyll-feed
  - jekyll-remote-theme

navbar-links:
  About Me: "about"

social-network-links:
  email: "ppluijten@gmail.com"
  rss: true
  github: ppluijten

share-links-active:
  twitter: true
  facebook: true
  linkedin: true

feed_show_tags: true
feed_show_excerpt: true
excerpt_length: 50
rss-description: The feed for ppluijten.dev

permalink: /:year-:month-:day-:title/

google_analytics: G-EDH3QRC6EY
